### ISSUE TITLE
Allow a timeout for the window

### ISSUE THREAD

**Issue by deajan** [cubiclesoft/messagebox-windows#1]
Hi,

using your messagebox-win tool which is quite nice.
It would be cool to have a /timeout=N where N is the number of seconds before the window closes.

Best regards.

**Comment by cubiclesoft** [comment]
I just added a /w option where it is possible to specify the number of milliseconds to wait.  Note that the method used relies on an undocumented API.  That means it could go away or change with a future version of Windows.  The API was added to Windows XP and later.

**Comment by deajan** [comment]
Wow, that was fast, Thank you alot !
Hmmm... undocumented windows API... Well I guess when using this kind of executable, you'll live with the fact that it may not work one day :)
Successfully tested on Win10 x64 1809 so far.
I'll have a quick test run on a Win7 machine once I get hands on it.

**Comment by cubiclesoft** [comment]
You're welcome.  I have a general policy of having no open issues on my issue trackers across all projects.  Glad to hear it works.

**Comment by deajan** [comment]
Works great on Win7 too :)
Thanks again.
