### ISSUE TITLE
Using carriage return / line feed in message

### ISSUE THREAD

**Issue by Borgquite** [cubiclesoft/messagebox-windows#2]
Great code! Can't see how it's possible to insert carriage returns or linefeeds from the command line into the message though (as supported by lpText https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messagebox)

Have tried \n, /n, \r and \r but none seem to work

**Comment by cubiclesoft** [comment]
Actually, you can do that with the current software BUT it is really convoluted.  The Command Prompt command-line parser will normally stop parsing the command line the moment it encounters a newline.  It's actually a limitation of Command Prompt.

This works but is extremely ugly:

```
C:\messagebox>(set \n=^^^
More?
More? ^
More?
More? )

C:\messagebox>messagebox.exe /v ^"This is a test%\n%Woot.^" "It works!"
Arguments:
        argv[0] = messagebox.exe
        argv[1] = /v
        argv[2] = This is a test
Woot.
        argv[3] = It works!

MessageBox(
        hWnd = 0x006F1114,
        lpText = This is a test
Woot.,
        lpCaption = It works!,
        uType = MB_OK | MB_DEFBUTTON1 | MB_APPLMODAL
);
```

The first command defines an escaped newline character (using a caret) as an environment variable named `\n`.  The second command uses a highly escaped string with the newly defined environment variable.  Note that the surrounding quotes are escaped too.

I agree that re-parsing that input parameter for common escape sequences might make it friendlier to use in anything that uses cmd.exe - batch files, Command Prompt, and common scripting languages that use a shell wrapper.

**Comment by Borgquite** [comment]
Thanks - I don't suppose you could translate that into PowerShell? :)

**Comment by cubiclesoft** [comment]
Use the backtick.  This should work (untested since I don't use PowerShell):

```
messagebox.exe /v "This is a test.`nWoot." "It works!"
```

Source:  https://devblogs.microsoft.com/scripting/powertip-new-lines-with-powershell/

**Comment by Borgquite** [comment]
Hi - thanks :) Backtick works perfectly.
Many thanks!

**Comment by cubiclesoft** [comment]
Added `/p` option to parse the text to display for `\n` newline sequences.  It's better now.
